include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_non_null_assertion: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_final_locals: false
    prefer_final_fields: false
    prefer_const_constructors_in_immutables: false
    curly_braces_in_flow_control_structures: false
    unnecessary_brace_in_string_interps: false
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
