include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # مؤقتًا: علق القاعدة التي تسبب 366 تحذير
    prefer_const_constructors: true
    
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
